language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.8
    - DB =postgres
addons:
  postgresql: "9.3"

# command to install dependencies
install:

    - pip install -r requirements.txt
    - pip install selenium
    - pip install model_mommy




# command to run tests
script: python manage.py test apps.account --settings=settings.dev 

notifications:
  email:
    recipients:

      - arunghosh@gmail.com 
      - sabareeshk1991@gmail.com
