language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.8
    - DB =postgres
addons:
    postgresql:	"9.4.1"

# command to install dependencies
install:

    - pip install -r requirements.txt
    - pip install selenium
    - pip install model_mommy

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


# command to run tests
script: python manage.py test apps.account --settings=settings.dev





