language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.8
addons:
    postgresql:	"9.4.1"

# command to install dependencies
install:
  
    - pip install -r requirements.txt
    - pip install selenium



# command to run tests
script: python manage.py test apps.utils --settings=settings.dev
 



