language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.8
addons:
    postgresql:	"9.4.1"

# command to install dependencies
install:
  
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

# command to run tests
script: python manage.py apps.utils test --settings=settings.dev
 



